# This is a basic workflow to help you get started with Actions

name: Actualiza_productos_de_UDD

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
    push:
        branches: master
        paths: 'input/UDD/*.csv'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Actualiza_productos_de_UDD:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Sets up python
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
          python-version: 3.7

    # Runs a set of commands using the runners shell
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: generate products from UDD
      run: cd src; python UDD.py

    - uses: peter-evans/create-pull-request@v2
      with:
          commit_message: "Por favor confirma que esta todo bien"
          title: "Se actualizo el input de la UDD, y generamos los productos correspondientes"
          branch-suffix: timestamp
          committer: minciencia github bot <actions@github.com>
          reviewers: pdaire, fzmolina, raliaga, dna33, scornejo, MinCiencia
          base: master

    - name: update_API
      run: |
        curl -u "${{ secrets.DO_INT_USER }}:${{ secrets.DO_INT_PASS }}" \
        -H 'Accept: application/vnd.github.everest-preview+json'  "https://api.github.com/repos/Data-Observatory/covid19-API/dispatches" \
        -d '{"event_type": "update_please_from_UDD"}'



